namespace Troianos_RAT
{
	// Token: 0x0200000E RID: 14
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Form1 : global::System.Windows.Forms.Form
	{
		// Token: 0x060000F3 RID: 243 RVA: 0x001E1310 File Offset: 0x001DF710
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x060000F4 RID: 244 RVA: 0x001E1360 File Offset: 0x001DF760
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::Troianos_RAT.Form1));
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new global::System.Windows.Forms.DataGridViewCellStyle();
			this.StatusStrip1 = new global::System.Windows.Forms.StatusStrip();
			this.ToolStripStatusLabel1 = new global::System.Windows.Forms.ToolStripStatusLabel();
			this.ToolStripStatusLabel3 = new global::System.Windows.Forms.ToolStripStatusLabel();
			this.ToolStripStatusLabel5 = new global::System.Windows.Forms.ToolStripStatusLabel();
			this.ToolStripStatusLabel4 = new global::System.Windows.Forms.ToolStripStatusLabel();
			this.conz = new global::System.Windows.Forms.ToolStripStatusLabel();
			this.upl = new global::System.Windows.Forms.ToolStripStatusLabel();
			this.dwn = new global::System.Windows.Forms.ToolStripStatusLabel();
			this.ContextMenuStrip1 = new global::System.Windows.Forms.ContextMenuStrip(this.components);
			this.ManagerToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.RunFileToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.FromLinkToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.FromDiskToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.ScriptToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.RemoteDesktopToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.RemoteCamToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.MicrophoneToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.GetPasswordsToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.KeyloggerToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.SacanearToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.OpenChatToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.ServerToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.UpdateToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.FromDISKToolStripMenuItem1 = new global::System.Windows.Forms.ToolStripMenuItem();
			this.FromLINKToolStripMenuItem1 = new global::System.Windows.Forms.ToolStripMenuItem();
			this.UninstallToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.RestartToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.CloseToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.DisconnectToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.RenameToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.OpenFolderToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.IMG2 = new global::System.Windows.Forms.ImageList(this.components);
			this.Timer1 = new global::System.Windows.Forms.Timer(this.components);
			this.ColorDialog1 = new global::System.Windows.Forms.ColorDialog();
			this.ColorDialog2 = new global::System.Windows.Forms.ColorDialog();
			this.L1 = new global::Troianos_RAT.L1();
			this.Pp1 = new global::Troianos_RAT.Pp1();
			this.StatusStrip1.SuspendLayout();
			this.ContextMenuStrip1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.L1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.Pp1).BeginInit();
			this.SuspendLayout();
			this.StatusStrip1.BackColor = global::System.Drawing.Color.Black;
			this.StatusStrip1.Items.AddRange(new global::System.Windows.Forms.ToolStripItem[]
			{
				this.ToolStripStatusLabel1,
				this.ToolStripStatusLabel3,
				this.ToolStripStatusLabel5,
				this.ToolStripStatusLabel4,
				this.conz,
				this.upl,
				this.dwn
			});
			global::System.Windows.Forms.Control statusStrip = this.StatusStrip1;
			global::System.Drawing.Point location = new global::System.Drawing.Point(0, 339);
			statusStrip.Location = location;
			this.StatusStrip1.Name = "StatusStrip1";
			this.StatusStrip1.RenderMode = global::System.Windows.Forms.ToolStripRenderMode.Professional;
			global::System.Windows.Forms.Control statusStrip2 = this.StatusStrip1;
			global::System.Drawing.Size size = new global::System.Drawing.Size(865, 22);
			statusStrip2.Size = size;
			this.StatusStrip1.SizingGrip = false;
			this.StatusStrip1.TabIndex = 0;
			this.StatusStrip1.Tag = "1";
			this.StatusStrip1.Text = "StatusStrip1";
			this.ToolStripStatusLabel1.ActiveLinkColor = global::System.Drawing.Color.White;
			this.ToolStripStatusLabel1.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.ToolStripStatusLabel1.ForeColor = global::System.Drawing.Color.White;
			this.ToolStripStatusLabel1.IsLink = true;
			this.ToolStripStatusLabel1.LinkColor = global::System.Drawing.Color.White;
			this.ToolStripStatusLabel1.Name = "ToolStripStatusLabel1";
			global::System.Windows.Forms.ToolStripItem toolStripStatusLabel = this.ToolStripStatusLabel1;
			size = new global::System.Drawing.Size(49, 17);
			toolStripStatusLabel.Size = size;
			this.ToolStripStatusLabel1.Tag = "1";
			this.ToolStripStatusLabel1.Text = "[ Logs ]";
			this.ToolStripStatusLabel3.ActiveLinkColor = global::System.Drawing.Color.White;
			this.ToolStripStatusLabel3.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.ToolStripStatusLabel3.ForeColor = global::System.Drawing.Color.White;
			this.ToolStripStatusLabel3.IsLink = true;
			this.ToolStripStatusLabel3.LinkColor = global::System.Drawing.Color.White;
			this.ToolStripStatusLabel3.Name = "ToolStripStatusLabel3";
			global::System.Windows.Forms.ToolStripItem toolStripStatusLabel2 = this.ToolStripStatusLabel3;
			size = new global::System.Drawing.Size(91, 17);
			toolStripStatusLabel2.Size = size;
			this.ToolStripStatusLabel3.Text = "[ Criar Server ] ";
			this.ToolStripStatusLabel5.ActiveLinkColor = global::System.Drawing.Color.White;
			this.ToolStripStatusLabel5.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.ToolStripStatusLabel5.ForeColor = global::System.Drawing.Color.White;
			this.ToolStripStatusLabel5.IsLink = true;
			this.ToolStripStatusLabel5.LinkColor = global::System.Drawing.Color.White;
			this.ToolStripStatusLabel5.Name = "ToolStripStatusLabel5";
			global::System.Windows.Forms.ToolStripItem toolStripStatusLabel3 = this.ToolStripStatusLabel5;
			size = new global::System.Drawing.Size(102, 17);
			toolStripStatusLabel3.Size = size;
			this.ToolStripStatusLabel5.Text = "[ Configurações ]";
			this.ToolStripStatusLabel4.ActiveLinkColor = global::System.Drawing.Color.White;
			this.ToolStripStatusLabel4.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.ToolStripStatusLabel4.ForeColor = global::System.Drawing.Color.White;
			this.ToolStripStatusLabel4.IsLink = true;
			this.ToolStripStatusLabel4.LinkColor = global::System.Drawing.Color.White;
			this.ToolStripStatusLabel4.Name = "ToolStripStatusLabel4";
			global::System.Windows.Forms.ToolStripItem toolStripStatusLabel4 = this.ToolStripStatusLabel4;
			size = new global::System.Drawing.Size(69, 17);
			toolStripStatusLabel4.Size = size;
			this.ToolStripStatusLabel4.Text = "[ Créditos ]";
			this.conz.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.conz.ForeColor = global::System.Drawing.Color.White;
			this.conz.LinkColor = global::System.Drawing.Color.White;
			this.conz.Name = "conz";
			global::System.Windows.Forms.ToolStripItem conz = this.conz;
			size = new global::System.Drawing.Size(86, 17);
			conz.Size = size;
			this.conz.Text = "Conexões [ 0 ]";
			this.upl.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.upl.ForeColor = global::System.Drawing.Color.White;
			this.upl.LinkColor = global::System.Drawing.Color.White;
			this.upl.Name = "upl";
			global::System.Windows.Forms.ToolStripItem upl = this.upl;
			size = new global::System.Drawing.Size(93, 17);
			upl.Size = size;
			this.upl.Text = "Envio [ 0 Bytes ]";
			this.dwn.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.dwn.ForeColor = global::System.Drawing.Color.White;
			this.dwn.LinkColor = global::System.Drawing.Color.White;
			this.dwn.Name = "dwn";
			global::System.Windows.Forms.ToolStripItem dwn = this.dwn;
			size = new global::System.Drawing.Size(106, 17);
			dwn.Size = size;
			this.dwn.Text = "Baixado [ 0 Bytes ]";
			this.ContextMenuStrip1.BackColor = global::System.Drawing.SystemColors.ActiveCaptionText;
			this.ContextMenuStrip1.Items.AddRange(new global::System.Windows.Forms.ToolStripItem[]
			{
				this.ManagerToolStripMenuItem,
				this.RunFileToolStripMenuItem,
				this.RemoteDesktopToolStripMenuItem,
				this.RemoteCamToolStripMenuItem,
				this.MicrophoneToolStripMenuItem,
				this.GetPasswordsToolStripMenuItem,
				this.KeyloggerToolStripMenuItem,
				this.SacanearToolStripMenuItem,
				this.OpenChatToolStripMenuItem,
				this.ServerToolStripMenuItem,
				this.OpenFolderToolStripMenuItem
			});
			this.ContextMenuStrip1.Name = "ContextMenuStrip1";
			this.ContextMenuStrip1.RenderMode = global::System.Windows.Forms.ToolStripRenderMode.Professional;
			global::System.Windows.Forms.Control contextMenuStrip = this.ContextMenuStrip1;
			size = new global::System.Drawing.Size(169, 268);
			contextMenuStrip.Size = size;
			this.ManagerToolStripMenuItem.BackColor = global::System.Drawing.Color.Black;
			this.ManagerToolStripMenuItem.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.ManagerToolStripMenuItem.ForeColor = global::System.Drawing.Color.White;
			this.ManagerToolStripMenuItem.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("ManagerToolStripMenuItem.Image");
			this.ManagerToolStripMenuItem.Name = "ManagerToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem managerToolStripMenuItem = this.ManagerToolStripMenuItem;
			size = new global::System.Drawing.Size(168, 22);
			managerToolStripMenuItem.Size = size;
			this.ManagerToolStripMenuItem.Text = "Gerenciador";
			this.RunFileToolStripMenuItem.BackColor = global::System.Drawing.Color.Black;
			this.RunFileToolStripMenuItem.DropDownItems.AddRange(new global::System.Windows.Forms.ToolStripItem[]
			{
				this.FromLinkToolStripMenuItem,
				this.FromDiskToolStripMenuItem,
				this.ScriptToolStripMenuItem
			});
			this.RunFileToolStripMenuItem.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.RunFileToolStripMenuItem.ForeColor = global::System.Drawing.Color.White;
			this.RunFileToolStripMenuItem.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("RunFileToolStripMenuItem.Image");
			this.RunFileToolStripMenuItem.Name = "RunFileToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem runFileToolStripMenuItem = this.RunFileToolStripMenuItem;
			size = new global::System.Drawing.Size(168, 22);
			runFileToolStripMenuItem.Size = size;
			this.RunFileToolStripMenuItem.Text = "Executar Arquivo";
			this.FromLinkToolStripMenuItem.BackColor = global::System.Drawing.Color.Black;
			this.FromLinkToolStripMenuItem.ForeColor = global::System.Drawing.Color.White;
			this.FromLinkToolStripMenuItem.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("FromLinkToolStripMenuItem.Image");
			this.FromLinkToolStripMenuItem.Name = "FromLinkToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem fromLinkToolStripMenuItem = this.FromLinkToolStripMenuItem;
			size = new global::System.Drawing.Size(185, 22);
			fromLinkToolStripMenuItem.Size = size;
			this.FromLinkToolStripMenuItem.Text = "Apartir do Link";
			this.FromDiskToolStripMenuItem.BackColor = global::System.Drawing.SystemColors.ActiveCaptionText;
			this.FromDiskToolStripMenuItem.ForeColor = global::System.Drawing.Color.White;
			this.FromDiskToolStripMenuItem.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("FromDiskToolStripMenuItem.Image");
			this.FromDiskToolStripMenuItem.Name = "FromDiskToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem fromDiskToolStripMenuItem = this.FromDiskToolStripMenuItem;
			size = new global::System.Drawing.Size(185, 22);
			fromDiskToolStripMenuItem.Size = size;
			this.FromDiskToolStripMenuItem.Text = "Apartir do PC";
			this.ScriptToolStripMenuItem.BackColor = global::System.Drawing.SystemColors.ActiveCaptionText;
			this.ScriptToolStripMenuItem.ForeColor = global::System.Drawing.Color.White;
			this.ScriptToolStripMenuItem.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("ScriptToolStripMenuItem.Image");
			this.ScriptToolStripMenuItem.Name = "ScriptToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem scriptToolStripMenuItem = this.ScriptToolStripMenuItem;
			size = new global::System.Drawing.Size(185, 22);
			scriptToolStripMenuItem.Size = size;
			this.ScriptToolStripMenuItem.Text = "Apartir do Comando";
			this.ScriptToolStripMenuItem.Visible = false;
			this.RemoteDesktopToolStripMenuItem.BackColor = global::System.Drawing.Color.Black;
			this.RemoteDesktopToolStripMenuItem.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.RemoteDesktopToolStripMenuItem.ForeColor = global::System.Drawing.Color.White;
			this.RemoteDesktopToolStripMenuItem.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("RemoteDesktopToolStripMenuItem.Image");
			this.RemoteDesktopToolStripMenuItem.Name = "RemoteDesktopToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem remoteDesktopToolStripMenuItem = this.RemoteDesktopToolStripMenuItem;
			size = new global::System.Drawing.Size(168, 22);
			remoteDesktopToolStripMenuItem.Size = size;
			this.RemoteDesktopToolStripMenuItem.Text = "Tela Remota";
			this.RemoteCamToolStripMenuItem.BackColor = global::System.Drawing.Color.Black;
			this.RemoteCamToolStripMenuItem.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.RemoteCamToolStripMenuItem.ForeColor = global::System.Drawing.Color.White;
			this.RemoteCamToolStripMenuItem.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("RemoteCamToolStripMenuItem.Image");
			this.RemoteCamToolStripMenuItem.Name = "RemoteCamToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem remoteCamToolStripMenuItem = this.RemoteCamToolStripMenuItem;
			size = new global::System.Drawing.Size(168, 22);
			remoteCamToolStripMenuItem.Size = size;
			this.RemoteCamToolStripMenuItem.Text = "WebCam Remota";
			this.MicrophoneToolStripMenuItem.BackColor = global::System.Drawing.Color.Black;
			this.MicrophoneToolStripMenuItem.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.MicrophoneToolStripMenuItem.ForeColor = global::System.Drawing.Color.White;
			this.MicrophoneToolStripMenuItem.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("MicrophoneToolStripMenuItem.Image");
			this.MicrophoneToolStripMenuItem.Name = "MicrophoneToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem microphoneToolStripMenuItem = this.MicrophoneToolStripMenuItem;
			size = new global::System.Drawing.Size(168, 22);
			microphoneToolStripMenuItem.Size = size;
			this.MicrophoneToolStripMenuItem.Text = "Microfone";
			this.GetPasswordsToolStripMenuItem.BackColor = global::System.Drawing.Color.Black;
			this.GetPasswordsToolStripMenuItem.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.GetPasswordsToolStripMenuItem.ForeColor = global::System.Drawing.Color.White;
			this.GetPasswordsToolStripMenuItem.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("GetPasswordsToolStripMenuItem.Image");
			this.GetPasswordsToolStripMenuItem.Name = "GetPasswordsToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem getPasswordsToolStripMenuItem = this.GetPasswordsToolStripMenuItem;
			size = new global::System.Drawing.Size(168, 22);
			getPasswordsToolStripMenuItem.Size = size;
			this.GetPasswordsToolStripMenuItem.Text = "Capturar Senhas";
			this.KeyloggerToolStripMenuItem.BackColor = global::System.Drawing.Color.Black;
			this.KeyloggerToolStripMenuItem.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.KeyloggerToolStripMenuItem.ForeColor = global::System.Drawing.Color.White;
			this.KeyloggerToolStripMenuItem.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("KeyloggerToolStripMenuItem.Image");
			this.KeyloggerToolStripMenuItem.Name = "KeyloggerToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem keyloggerToolStripMenuItem = this.KeyloggerToolStripMenuItem;
			size = new global::System.Drawing.Size(168, 22);
			keyloggerToolStripMenuItem.Size = size;
			this.KeyloggerToolStripMenuItem.Text = "Capturar Digitos";
			this.SacanearToolStripMenuItem.BackColor = global::System.Drawing.Color.Black;
			this.SacanearToolStripMenuItem.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold);
			this.SacanearToolStripMenuItem.ForeColor = global::System.Drawing.Color.White;
			this.SacanearToolStripMenuItem.Image = global::Troianos_RAT.My.Resources.Resources.poison_98648_640;
			this.SacanearToolStripMenuItem.ImageTransparentColor = global::System.Drawing.Color.Black;
			this.SacanearToolStripMenuItem.Name = "SacanearToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem sacanearToolStripMenuItem = this.SacanearToolStripMenuItem;
			size = new global::System.Drawing.Size(168, 22);
			sacanearToolStripMenuItem.Size = size;
			this.SacanearToolStripMenuItem.Text = "Sacanear";
			this.OpenChatToolStripMenuItem.BackColor = global::System.Drawing.Color.Black;
			this.OpenChatToolStripMenuItem.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.OpenChatToolStripMenuItem.ForeColor = global::System.Drawing.Color.White;
			this.OpenChatToolStripMenuItem.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("OpenChatToolStripMenuItem.Image");
			this.OpenChatToolStripMenuItem.Name = "OpenChatToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem openChatToolStripMenuItem = this.OpenChatToolStripMenuItem;
			size = new global::System.Drawing.Size(168, 22);
			openChatToolStripMenuItem.Size = size;
			this.OpenChatToolStripMenuItem.Text = "Abrir Chat";
			this.ServerToolStripMenuItem.BackColor = global::System.Drawing.Color.Black;
			this.ServerToolStripMenuItem.DropDownItems.AddRange(new global::System.Windows.Forms.ToolStripItem[]
			{
				this.UpdateToolStripMenuItem,
				this.UninstallToolStripMenuItem,
				this.RestartToolStripMenuItem,
				this.CloseToolStripMenuItem,
				this.DisconnectToolStripMenuItem,
				this.RenameToolStripMenuItem
			});
			this.ServerToolStripMenuItem.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.ServerToolStripMenuItem.ForeColor = global::System.Drawing.Color.White;
			this.ServerToolStripMenuItem.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("ServerToolStripMenuItem.Image");
			this.ServerToolStripMenuItem.Name = "ServerToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem serverToolStripMenuItem = this.ServerToolStripMenuItem;
			size = new global::System.Drawing.Size(168, 22);
			serverToolStripMenuItem.Size = size;
			this.ServerToolStripMenuItem.Text = "Servidor";
			this.UpdateToolStripMenuItem.BackColor = global::System.Drawing.SystemColors.ActiveCaptionText;
			this.UpdateToolStripMenuItem.DropDownItems.AddRange(new global::System.Windows.Forms.ToolStripItem[]
			{
				this.FromDISKToolStripMenuItem1,
				this.FromLINKToolStripMenuItem1
			});
			this.UpdateToolStripMenuItem.ForeColor = global::System.Drawing.Color.White;
			this.UpdateToolStripMenuItem.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("UpdateToolStripMenuItem.Image");
			this.UpdateToolStripMenuItem.Name = "UpdateToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem updateToolStripMenuItem = this.UpdateToolStripMenuItem;
			size = new global::System.Drawing.Size(143, 22);
			updateToolStripMenuItem.Size = size;
			this.UpdateToolStripMenuItem.Text = "Atualizar";
			this.FromDISKToolStripMenuItem1.BackColor = global::System.Drawing.SystemColors.ActiveCaptionText;
			this.FromDISKToolStripMenuItem1.ForeColor = global::System.Drawing.Color.LightSteelBlue;
			this.FromDISKToolStripMenuItem1.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("FromDISKToolStripMenuItem1.Image");
			this.FromDISKToolStripMenuItem1.Name = "FromDISKToolStripMenuItem1";
			global::System.Windows.Forms.ToolStripItem fromDISKToolStripMenuItem = this.FromDISKToolStripMenuItem1;
			size = new global::System.Drawing.Size(156, 22);
			fromDISKToolStripMenuItem.Size = size;
			this.FromDISKToolStripMenuItem1.Text = "Apartir do PC";
			this.FromLINKToolStripMenuItem1.BackColor = global::System.Drawing.SystemColors.ActiveCaptionText;
			this.FromLINKToolStripMenuItem1.ForeColor = global::System.Drawing.Color.LightSteelBlue;
			this.FromLINKToolStripMenuItem1.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("FromLINKToolStripMenuItem1.Image");
			this.FromLINKToolStripMenuItem1.Name = "FromLINKToolStripMenuItem1";
			global::System.Windows.Forms.ToolStripItem fromLINKToolStripMenuItem = this.FromLINKToolStripMenuItem1;
			size = new global::System.Drawing.Size(156, 22);
			fromLINKToolStripMenuItem.Size = size;
			this.FromLINKToolStripMenuItem1.Text = "Apartir do Link";
			this.UninstallToolStripMenuItem.BackColor = global::System.Drawing.SystemColors.ActiveCaptionText;
			this.UninstallToolStripMenuItem.ForeColor = global::System.Drawing.Color.White;
			this.UninstallToolStripMenuItem.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("UninstallToolStripMenuItem.Image");
			this.UninstallToolStripMenuItem.Name = "UninstallToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem uninstallToolStripMenuItem = this.UninstallToolStripMenuItem;
			size = new global::System.Drawing.Size(143, 22);
			uninstallToolStripMenuItem.Size = size;
			this.UninstallToolStripMenuItem.Text = "Desinstalar";
			this.RestartToolStripMenuItem.BackColor = global::System.Drawing.SystemColors.ActiveCaptionText;
			this.RestartToolStripMenuItem.ForeColor = global::System.Drawing.Color.White;
			this.RestartToolStripMenuItem.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("RestartToolStripMenuItem.Image");
			this.RestartToolStripMenuItem.Name = "RestartToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem restartToolStripMenuItem = this.RestartToolStripMenuItem;
			size = new global::System.Drawing.Size(143, 22);
			restartToolStripMenuItem.Size = size;
			this.RestartToolStripMenuItem.Text = "Reiniciar";
			this.CloseToolStripMenuItem.BackColor = global::System.Drawing.SystemColors.ActiveCaptionText;
			this.CloseToolStripMenuItem.ForeColor = global::System.Drawing.Color.White;
			this.CloseToolStripMenuItem.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("CloseToolStripMenuItem.Image");
			this.CloseToolStripMenuItem.Name = "CloseToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem closeToolStripMenuItem = this.CloseToolStripMenuItem;
			size = new global::System.Drawing.Size(143, 22);
			closeToolStripMenuItem.Size = size;
			this.CloseToolStripMenuItem.Text = "Fechar";
			this.DisconnectToolStripMenuItem.BackColor = global::System.Drawing.SystemColors.ActiveCaptionText;
			this.DisconnectToolStripMenuItem.ForeColor = global::System.Drawing.Color.White;
			this.DisconnectToolStripMenuItem.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("DisconnectToolStripMenuItem.Image");
			this.DisconnectToolStripMenuItem.Name = "DisconnectToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem disconnectToolStripMenuItem = this.DisconnectToolStripMenuItem;
			size = new global::System.Drawing.Size(143, 22);
			disconnectToolStripMenuItem.Size = size;
			this.DisconnectToolStripMenuItem.Text = "Desconectar";
			this.RenameToolStripMenuItem.BackColor = global::System.Drawing.SystemColors.ActiveCaptionText;
			this.RenameToolStripMenuItem.ForeColor = global::System.Drawing.Color.White;
			this.RenameToolStripMenuItem.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("RenameToolStripMenuItem.Image");
			this.RenameToolStripMenuItem.Name = "RenameToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem renameToolStripMenuItem = this.RenameToolStripMenuItem;
			size = new global::System.Drawing.Size(143, 22);
			renameToolStripMenuItem.Size = size;
			this.RenameToolStripMenuItem.Text = "Renomear";
			this.OpenFolderToolStripMenuItem.BackColor = global::System.Drawing.Color.Black;
			this.OpenFolderToolStripMenuItem.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.OpenFolderToolStripMenuItem.ForeColor = global::System.Drawing.Color.White;
			this.OpenFolderToolStripMenuItem.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("OpenFolderToolStripMenuItem.Image");
			this.OpenFolderToolStripMenuItem.Name = "OpenFolderToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem openFolderToolStripMenuItem = this.OpenFolderToolStripMenuItem;
			size = new global::System.Drawing.Size(168, 22);
			openFolderToolStripMenuItem.Size = size;
			this.OpenFolderToolStripMenuItem.Text = "Abrir Pasta";
			this.IMG2.ImageStream = (global::System.Windows.Forms.ImageListStreamer)componentResourceManager.GetObject("IMG2.ImageStream");
			this.IMG2.TransparentColor = global::System.Drawing.Color.Transparent;
			this.IMG2.Images.SetKeyName(0, "--.png");
			this.IMG2.Images.SetKeyName(1, "AD.png");
			this.IMG2.Images.SetKeyName(2, "AE.png");
			this.IMG2.Images.SetKeyName(3, "AF.png");
			this.IMG2.Images.SetKeyName(4, "AG.png");
			this.IMG2.Images.SetKeyName(5, "AI.png");
			this.IMG2.Images.SetKeyName(6, "AL.png");
			this.IMG2.Images.SetKeyName(7, "AM.png");
			this.IMG2.Images.SetKeyName(8, "AN.png");
			this.IMG2.Images.SetKeyName(9, "AO.png");
			this.IMG2.Images.SetKeyName(10, "AQ.png");
			this.IMG2.Images.SetKeyName(11, "AR.png");
			this.IMG2.Images.SetKeyName(12, "AS.png");
			this.IMG2.Images.SetKeyName(13, "AT.png");
			this.IMG2.Images.SetKeyName(14, "AU.png");
			this.IMG2.Images.SetKeyName(15, "AW.png");
			this.IMG2.Images.SetKeyName(16, "AX.png");
			this.IMG2.Images.SetKeyName(17, "AZ.png");
			this.IMG2.Images.SetKeyName(18, "BA.png");
			this.IMG2.Images.SetKeyName(19, "BB.png");
			this.IMG2.Images.SetKeyName(20, "BD.png");
			this.IMG2.Images.SetKeyName(21, "BE.png");
			this.IMG2.Images.SetKeyName(22, "BF.png");
			this.IMG2.Images.SetKeyName(23, "BG.png");
			this.IMG2.Images.SetKeyName(24, "BH.png");
			this.IMG2.Images.SetKeyName(25, "BI.png");
			this.IMG2.Images.SetKeyName(26, "BJ.png");
			this.IMG2.Images.SetKeyName(27, "BL.png");
			this.IMG2.Images.SetKeyName(28, "BM.png");
			this.IMG2.Images.SetKeyName(29, "BN.png");
			this.IMG2.Images.SetKeyName(30, "BO.png");
			this.IMG2.Images.SetKeyName(31, "BR.png");
			this.IMG2.Images.SetKeyName(32, "BS.png");
			this.IMG2.Images.SetKeyName(33, "BT.png");
			this.IMG2.Images.SetKeyName(34, "BW.png");
			this.IMG2.Images.SetKeyName(35, "BY.png");
			this.IMG2.Images.SetKeyName(36, "BZ.png");
			this.IMG2.Images.SetKeyName(37, "CA.png");
			this.IMG2.Images.SetKeyName(38, "CC.png");
			this.IMG2.Images.SetKeyName(39, "CD.png");
			this.IMG2.Images.SetKeyName(40, "CF.png");
			this.IMG2.Images.SetKeyName(41, "CG.png");
			this.IMG2.Images.SetKeyName(42, "CH.png");
			this.IMG2.Images.SetKeyName(43, "CI.png");
			this.IMG2.Images.SetKeyName(44, "CK.png");
			this.IMG2.Images.SetKeyName(45, "CL.png");
			this.IMG2.Images.SetKeyName(46, "CM.png");
			this.IMG2.Images.SetKeyName(47, "CN.png");
			this.IMG2.Images.SetKeyName(48, "CO.png");
			this.IMG2.Images.SetKeyName(49, "CR.png");
			this.IMG2.Images.SetKeyName(50, "CU.png");
			this.IMG2.Images.SetKeyName(51, "CV.png");
			this.IMG2.Images.SetKeyName(52, "CW.png");
			this.IMG2.Images.SetKeyName(53, "CX.png");
			this.IMG2.Images.SetKeyName(54, "CY.png");
			this.IMG2.Images.SetKeyName(55, "CZ.png");
			this.IMG2.Images.SetKeyName(56, "DE.png");
			this.IMG2.Images.SetKeyName(57, "DJ.png");
			this.IMG2.Images.SetKeyName(58, "DK.png");
			this.IMG2.Images.SetKeyName(59, "DM.png");
			this.IMG2.Images.SetKeyName(60, "DO.png");
			this.IMG2.Images.SetKeyName(61, "DZ.png");
			this.IMG2.Images.SetKeyName(62, "EC.png");
			this.IMG2.Images.SetKeyName(63, "EE.png");
			this.IMG2.Images.SetKeyName(64, "EG.png");
			this.IMG2.Images.SetKeyName(65, "EH.png");
			this.IMG2.Images.SetKeyName(66, "ER.png");
			this.IMG2.Images.SetKeyName(67, "ES.png");
			this.IMG2.Images.SetKeyName(68, "ET.png");
			this.IMG2.Images.SetKeyName(69, "EU.png");
			this.IMG2.Images.SetKeyName(70, "FI.png");
			this.IMG2.Images.SetKeyName(71, "FJ.png");
			this.IMG2.Images.SetKeyName(72, "FK.png");
			this.IMG2.Images.SetKeyName(73, "FM.png");
			this.IMG2.Images.SetKeyName(74, "FO.png");
			this.IMG2.Images.SetKeyName(75, "FR.png");
			this.IMG2.Images.SetKeyName(76, "GA.png");
			this.IMG2.Images.SetKeyName(77, "GB.png");
			this.IMG2.Images.SetKeyName(78, "GD.png");
			this.IMG2.Images.SetKeyName(79, "GE.png");
			this.IMG2.Images.SetKeyName(80, "GG.png");
			this.IMG2.Images.SetKeyName(81, "GH.png");
			this.IMG2.Images.SetKeyName(82, "GI.png");
			this.IMG2.Images.SetKeyName(83, "GL.png");
			this.IMG2.Images.SetKeyName(84, "GM.png");
			this.IMG2.Images.SetKeyName(85, "GN.png");
			this.IMG2.Images.SetKeyName(86, "GQ.png");
			this.IMG2.Images.SetKeyName(87, "GR.png");
			this.IMG2.Images.SetKeyName(88, "GS.png");
			this.IMG2.Images.SetKeyName(89, "GT.png");
			this.IMG2.Images.SetKeyName(90, "GU.png");
			this.IMG2.Images.SetKeyName(91, "GW.png");
			this.IMG2.Images.SetKeyName(92, "GY.png");
			this.IMG2.Images.SetKeyName(93, "HK.png");
			this.IMG2.Images.SetKeyName(94, "HN.png");
			this.IMG2.Images.SetKeyName(95, "HR.png");
			this.IMG2.Images.SetKeyName(96, "HT.png");
			this.IMG2.Images.SetKeyName(97, "HU.png");
			this.IMG2.Images.SetKeyName(98, "IC.png");
			this.IMG2.Images.SetKeyName(99, "ID.png");
			this.IMG2.Images.SetKeyName(100, "IE.png");
			this.IMG2.Images.SetKeyName(101, "IL.png");
			this.IMG2.Images.SetKeyName(102, "IM.png");
			this.IMG2.Images.SetKeyName(103, "IN.png");
			this.IMG2.Images.SetKeyName(104, "IQ.png");
			this.IMG2.Images.SetKeyName(105, "IR.png");
			this.IMG2.Images.SetKeyName(106, "IS.png");
			this.IMG2.Images.SetKeyName(107, "IT.png");
			this.IMG2.Images.SetKeyName(108, "JE.png");
			this.IMG2.Images.SetKeyName(109, "JM.png");
			this.IMG2.Images.SetKeyName(110, "JO.png");
			this.IMG2.Images.SetKeyName(111, "JP.png");
			this.IMG2.Images.SetKeyName(112, "KE.png");
			this.IMG2.Images.SetKeyName(113, "KG.png");
			this.IMG2.Images.SetKeyName(114, "KH.png");
			this.IMG2.Images.SetKeyName(115, "KI.png");
			this.IMG2.Images.SetKeyName(116, "KM.png");
			this.IMG2.Images.SetKeyName(117, "KN.png");
			this.IMG2.Images.SetKeyName(118, "KP.png");
			this.IMG2.Images.SetKeyName(119, "KR.png");
			this.IMG2.Images.SetKeyName(120, "KW.png");
			this.IMG2.Images.SetKeyName(121, "KY.png");
			this.IMG2.Images.SetKeyName(122, "KZ.png");
			this.IMG2.Images.SetKeyName(123, "LA.png");
			this.IMG2.Images.SetKeyName(124, "LB.png");
			this.IMG2.Images.SetKeyName(125, "LC.png");
			this.IMG2.Images.SetKeyName(126, "LI.png");
			this.IMG2.Images.SetKeyName(127, "LK.png");
			this.IMG2.Images.SetKeyName(128, "LR.png");
			this.IMG2.Images.SetKeyName(129, "LS.png");
			this.IMG2.Images.SetKeyName(130, "LT.png");
			this.IMG2.Images.SetKeyName(131, "LU.png");
			this.IMG2.Images.SetKeyName(132, "LV.png");
			this.IMG2.Images.SetKeyName(133, "LY.png");
			this.IMG2.Images.SetKeyName(134, "MA.png");
			this.IMG2.Images.SetKeyName(135, "MC.png");
			this.IMG2.Images.SetKeyName(136, "MD.png");
			this.IMG2.Images.SetKeyName(137, "ME.png");
			this.IMG2.Images.SetKeyName(138, "MF.png");
			this.IMG2.Images.SetKeyName(139, "MG.png");
			this.IMG2.Images.SetKeyName(140, "MH.png");
			this.IMG2.Images.SetKeyName(141, "MK.png");
			this.IMG2.Images.SetKeyName(142, "ML.png");
			this.IMG2.Images.SetKeyName(143, "MM.png");
			this.IMG2.Images.SetKeyName(144, "MN.png");
			this.IMG2.Images.SetKeyName(145, "MO.png");
			this.IMG2.Images.SetKeyName(146, "MP.png");
			this.IMG2.Images.SetKeyName(147, "MQ.png");
			this.IMG2.Images.SetKeyName(148, "MR.png");
			this.IMG2.Images.SetKeyName(149, "MS.png");
			this.IMG2.Images.SetKeyName(150, "MT.png");
			this.IMG2.Images.SetKeyName(151, "MU.png");
			this.IMG2.Images.SetKeyName(152, "MV.png");
			this.IMG2.Images.SetKeyName(153, "MW.png");
			this.IMG2.Images.SetKeyName(154, "MX.png");
			this.IMG2.Images.SetKeyName(155, "MY.png");
			this.IMG2.Images.SetKeyName(156, "MZ.png");
			this.IMG2.Images.SetKeyName(157, "NA.png");
			this.IMG2.Images.SetKeyName(158, "NC.png");
			this.IMG2.Images.SetKeyName(159, "NE.png");
			this.IMG2.Images.SetKeyName(160, "NF.png");
			this.IMG2.Images.SetKeyName(161, "NG.png");
			this.IMG2.Images.SetKeyName(162, "NI.png");
			this.IMG2.Images.SetKeyName(163, "NL.png");
			this.IMG2.Images.SetKeyName(164, "NO.png");
			this.IMG2.Images.SetKeyName(165, "NP.png");
			this.IMG2.Images.SetKeyName(166, "NR.png");
			this.IMG2.Images.SetKeyName(167, "NU.png");
			this.IMG2.Images.SetKeyName(168, "NZ.png");
			this.IMG2.Images.SetKeyName(169, "OM.png");
			this.IMG2.Images.SetKeyName(170, "PA.png");
			this.IMG2.Images.SetKeyName(171, "PE.png");
			this.IMG2.Images.SetKeyName(172, "PF.png");
			this.IMG2.Images.SetKeyName(173, "PG.png");
			this.IMG2.Images.SetKeyName(174, "PH.png");
			this.IMG2.Images.SetKeyName(175, "PK.png");
			this.IMG2.Images.SetKeyName(176, "PL.png");
			this.IMG2.Images.SetKeyName(177, "PN.png");
			this.IMG2.Images.SetKeyName(178, "PR.png");
			this.IMG2.Images.SetKeyName(179, "PS.png");
			this.IMG2.Images.SetKeyName(180, "PT.png");
			this.IMG2.Images.SetKeyName(181, "PW.png");
			this.IMG2.Images.SetKeyName(182, "PY.png");
			this.IMG2.Images.SetKeyName(183, "QA.png");
			this.IMG2.Images.SetKeyName(184, "RO.png");
			this.IMG2.Images.SetKeyName(185, "RS.png");
			this.IMG2.Images.SetKeyName(186, "RU.png");
			this.IMG2.Images.SetKeyName(187, "RW.png");
			this.IMG2.Images.SetKeyName(188, "SA.png");
			this.IMG2.Images.SetKeyName(189, "SB.png");
			this.IMG2.Images.SetKeyName(190, "SC.png");
			this.IMG2.Images.SetKeyName(191, "SD.png");
			this.IMG2.Images.SetKeyName(192, "SE.png");
			this.IMG2.Images.SetKeyName(193, "SG.png");
			this.IMG2.Images.SetKeyName(194, "SH.png");
			this.IMG2.Images.SetKeyName(195, "SI.png");
			this.IMG2.Images.SetKeyName(196, "SK.png");
			this.IMG2.Images.SetKeyName(197, "SL.png");
			this.IMG2.Images.SetKeyName(198, "SM.png");
			this.IMG2.Images.SetKeyName(199, "SN.png");
			this.IMG2.Images.SetKeyName(200, "SO.png");
			this.IMG2.Images.SetKeyName(201, "SR.png");
			this.IMG2.Images.SetKeyName(202, "SS.png");
			this.IMG2.Images.SetKeyName(203, "ST.png");
			this.IMG2.Images.SetKeyName(204, "SV.png");
			this.IMG2.Images.SetKeyName(205, "SY.png");
			this.IMG2.Images.SetKeyName(206, "SZ.png");
			this.IMG2.Images.SetKeyName(207, "TC.png");
			this.IMG2.Images.SetKeyName(208, "TD.png");
			this.IMG2.Images.SetKeyName(209, "TF.png");
			this.IMG2.Images.SetKeyName(210, "TG.png");
			this.IMG2.Images.SetKeyName(211, "TH.png");
			this.IMG2.Images.SetKeyName(212, "TJ.png");
			this.IMG2.Images.SetKeyName(213, "TK.png");
			this.IMG2.Images.SetKeyName(214, "TL.png");
			this.IMG2.Images.SetKeyName(215, "TM.png");
			this.IMG2.Images.SetKeyName(216, "TN.png");
			this.IMG2.Images.SetKeyName(217, "TO.png");
			this.IMG2.Images.SetKeyName(218, "TR.png");
			this.IMG2.Images.SetKeyName(219, "TT.png");
			this.IMG2.Images.SetKeyName(220, "TV.png");
			this.IMG2.Images.SetKeyName(221, "TW.png");
			this.IMG2.Images.SetKeyName(222, "TZ.png");
			this.IMG2.Images.SetKeyName(223, "UA.png");
			this.IMG2.Images.SetKeyName(224, "UG.png");
			this.IMG2.Images.SetKeyName(225, "UN.png");
			this.IMG2.Images.SetKeyName(226, "US.png");
			this.IMG2.Images.SetKeyName(227, "UY.png");
			this.IMG2.Images.SetKeyName(228, "UZ.png");
			this.IMG2.Images.SetKeyName(229, "VA.png");
			this.IMG2.Images.SetKeyName(230, "VC.png");
			this.IMG2.Images.SetKeyName(231, "VE.png");
			this.IMG2.Images.SetKeyName(232, "VG.png");
			this.IMG2.Images.SetKeyName(233, "VI.png");
			this.IMG2.Images.SetKeyName(234, "VN.png");
			this.IMG2.Images.SetKeyName(235, "VU.png");
			this.IMG2.Images.SetKeyName(236, "WF.png");
			this.IMG2.Images.SetKeyName(237, "WS.png");
			this.IMG2.Images.SetKeyName(238, "YE.png");
			this.IMG2.Images.SetKeyName(239, "YT.png");
			this.IMG2.Images.SetKeyName(240, "ZA.png");
			this.IMG2.Images.SetKeyName(241, "ZM.png");
			this.IMG2.Images.SetKeyName(242, "ZW.png");
			this.Timer1.Enabled = true;
			this.L1.AllowUserToAddRows = false;
			this.L1.AllowUserToDeleteRows = false;
			this.L1.BackgroundColor = global::System.Drawing.Color.Black;
			this.L1.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.L1.ClipboardCopyMode = global::System.Windows.Forms.DataGridViewClipboardCopyMode.Disable;
			this.L1.ColumnHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
			dataGridViewCellStyle.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle.BackColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle.Font = new global::System.Drawing.Font("Arial", 8f, global::System.Drawing.FontStyle.Bold);
			dataGridViewCellStyle.ForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle.SelectionBackColor = global::System.Drawing.SystemColors.Highlight;
			dataGridViewCellStyle.SelectionForeColor = global::System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle.WrapMode = global::System.Windows.Forms.DataGridViewTriState.True;
			this.L1.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle;
			this.L1.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			this.L1.ContextMenuStrip = this.ContextMenuStrip1;
			dataGridViewCellStyle2.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle2.BackColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle2.Font = new global::System.Drawing.Font("Arial", 8f, global::System.Drawing.FontStyle.Bold);
			dataGridViewCellStyle2.ForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle2.SelectionBackColor = global::System.Drawing.SystemColors.Highlight;
			dataGridViewCellStyle2.SelectionForeColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle2.WrapMode = global::System.Windows.Forms.DataGridViewTriState.False;
			this.L1.DefaultCellStyle = dataGridViewCellStyle2;
			this.L1.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.L1.EnableHeadersVisualStyles = false;
			this.L1.Font = new global::System.Drawing.Font("Arial", 8f, global::System.Drawing.FontStyle.Bold);
			this.L1.GridColor = global::System.Drawing.Color.LightSteelBlue;
			global::System.Windows.Forms.Control l = this.L1;
			location = new global::System.Drawing.Point(0, 0);
			l.Location = location;
			this.L1.Name = "L1";
			this.L1.ReadOnly = true;
			this.L1.RowHeadersVisible = false;
			this.L1.SelectionMode = global::System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			this.L1.ShowCellErrors = false;
			this.L1.ShowEditingIcon = false;
			this.L1.ShowRowErrors = false;
			global::System.Windows.Forms.Control l2 = this.L1;
			size = new global::System.Drawing.Size(865, 339);
			l2.Size = size;
			this.L1.TabIndex = 2;
			this.Pp1.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.Pp1.Dock = global::System.Windows.Forms.DockStyle.Fill;
			global::System.Windows.Forms.Control pp = this.Pp1;
			location = new global::System.Drawing.Point(0, 0);
			pp.Location = location;
			this.Pp1.Name = "Pp1";
			global::System.Windows.Forms.Control pp2 = this.Pp1;
			size = new global::System.Drawing.Size(865, 361);
			pp2.Size = size;
			this.Pp1.TabIndex = 3;
			this.Pp1.TabStop = false;
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = global::System.Drawing.Color.Black;
			size = new global::System.Drawing.Size(865, 361);
			this.ClientSize = size;
			this.Controls.Add(this.L1);
			this.Controls.Add(this.StatusStrip1);
			this.Controls.Add(this.Pp1);
			this.ForeColor = global::System.Drawing.Color.White;
			this.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
			this.Name = "Form1";
			this.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.StatusStrip1.ResumeLayout(false);
			this.StatusStrip1.PerformLayout();
			this.ContextMenuStrip1.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.L1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.Pp1).EndInit();
			this.ResumeLayout(false);
			this.PerformLayout();
		}

		// Token: 0x0400007D RID: 125
		private global::System.ComponentModel.IContainer components;
	}
}
