namespace Troianos_RAT
{
	// Token: 0x0200001E RID: 30
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class script : global::System.Windows.Forms.Form
	{
		// Token: 0x06000362 RID: 866 RVA: 0x001F821C File Offset: 0x001F661C
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06000363 RID: 867 RVA: 0x001F826C File Offset: 0x001F666C
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::Troianos_RAT.script));
			this.Button15 = new global::System.Windows.Forms.Button();
			this.Button16 = new global::System.Windows.Forms.Button();
			this.Button17 = new global::System.Windows.Forms.Button();
			this.Button18 = new global::System.Windows.Forms.Button();
			this.Button19 = new global::System.Windows.Forms.Button();
			this.Button20 = new global::System.Windows.Forms.Button();
			this.Button21 = new global::System.Windows.Forms.Button();
			this.Button8 = new global::System.Windows.Forms.Button();
			this.Button9 = new global::System.Windows.Forms.Button();
			this.Button10 = new global::System.Windows.Forms.Button();
			this.Button11 = new global::System.Windows.Forms.Button();
			this.Button12 = new global::System.Windows.Forms.Button();
			this.Button13 = new global::System.Windows.Forms.Button();
			this.Button14 = new global::System.Windows.Forms.Button();
			this.Button7 = new global::System.Windows.Forms.Button();
			this.Button6 = new global::System.Windows.Forms.Button();
			this.Button5 = new global::System.Windows.Forms.Button();
			this.Button4 = new global::System.Windows.Forms.Button();
			this.Button3 = new global::System.Windows.Forms.Button();
			this.Button2 = new global::System.Windows.Forms.Button();
			this.Button1 = new global::System.Windows.Forms.Button();
			this.TextBox1 = new global::System.Windows.Forms.TextBox();
			this.SuspendLayout();
			this.Button15.BackColor = global::System.Drawing.Color.Transparent;
			this.Button15.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button15.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control button = this.Button15;
			global::System.Drawing.Point location = new global::System.Drawing.Point(270, 200);
			button.Location = location;
			this.Button15.Name = "Button15";
			global::System.Windows.Forms.Control button2 = this.Button15;
			global::System.Drawing.Size size = new global::System.Drawing.Size(123, 26);
			button2.Size = size;
			this.Button15.TabIndex = 41;
			this.Button15.Text = "Tela Azul da Morte";
			this.Button15.UseVisualStyleBackColor = false;
			this.Button16.BackColor = global::System.Drawing.Color.Transparent;
			this.Button16.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button16.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control button3 = this.Button16;
			location = new global::System.Drawing.Point(270, 168);
			button3.Location = location;
			this.Button16.Name = "Button16";
			global::System.Windows.Forms.Control button4 = this.Button16;
			size = new global::System.Drawing.Size(123, 26);
			button4.Size = size;
			this.Button16.TabIndex = 40;
			this.Button16.Text = "Deletar System32";
			this.Button16.UseVisualStyleBackColor = false;
			this.Button17.BackColor = global::System.Drawing.Color.Transparent;
			this.Button17.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button17.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control button5 = this.Button17;
			location = new global::System.Drawing.Point(270, 136);
			button5.Location = location;
			this.Button17.Name = "Button17";
			global::System.Windows.Forms.Control button6 = this.Button17;
			size = new global::System.Drawing.Size(123, 26);
			button6.Size = size;
			this.Button17.TabIndex = 39;
			this.Button17.Text = "Criar Varios VBS";
			this.Button17.UseVisualStyleBackColor = false;
			this.Button18.BackColor = global::System.Drawing.Color.Transparent;
			this.Button18.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button18.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control button7 = this.Button18;
			location = new global::System.Drawing.Point(270, 105);
			button7.Location = location;
			this.Button18.Name = "Button18";
			global::System.Windows.Forms.Control button8 = this.Button18;
			size = new global::System.Drawing.Size(123, 25);
			button8.Size = size;
			this.Button18.TabIndex = 38;
			this.Button18.Text = "Bipe Sem Parar";
			this.Button18.UseVisualStyleBackColor = false;
			this.Button19.BackColor = global::System.Drawing.Color.Transparent;
			this.Button19.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button19.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control button9 = this.Button19;
			location = new global::System.Drawing.Point(270, 74);
			button9.Location = location;
			this.Button19.Name = "Button19";
			global::System.Windows.Forms.Control button10 = this.Button19;
			size = new global::System.Drawing.Size(123, 25);
			button10.Size = size;
			this.Button19.TabIndex = 37;
			this.Button19.Text = "Desativar Firewall";
			this.Button19.UseVisualStyleBackColor = false;
			this.Button20.BackColor = global::System.Drawing.Color.Transparent;
			this.Button20.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button20.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control button11 = this.Button20;
			location = new global::System.Drawing.Point(270, 43);
			button11.Location = location;
			this.Button20.Name = "Button20";
			global::System.Windows.Forms.Control button12 = this.Button20;
			size = new global::System.Drawing.Size(123, 25);
			button12.Size = size;
			this.Button20.TabIndex = 36;
			this.Button20.Text = "Abrir Site Shafou";
			this.Button20.UseVisualStyleBackColor = false;
			this.Button21.BackColor = global::System.Drawing.Color.Transparent;
			this.Button21.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button21.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control button13 = this.Button21;
			location = new global::System.Drawing.Point(270, 12);
			button13.Location = location;
			this.Button21.Name = "Button21";
			global::System.Windows.Forms.Control button14 = this.Button21;
			size = new global::System.Drawing.Size(123, 25);
			button14.Size = size;
			this.Button21.TabIndex = 35;
			this.Button21.Text = "Abrir Site Porno";
			this.Button21.UseVisualStyleBackColor = false;
			this.Button8.BackColor = global::System.Drawing.Color.Transparent;
			this.Button8.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button8.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control button15 = this.Button8;
			location = new global::System.Drawing.Point(141, 200);
			button15.Location = location;
			this.Button8.Name = "Button8";
			global::System.Windows.Forms.Control button16 = this.Button8;
			size = new global::System.Drawing.Size(123, 26);
			button16.Size = size;
			this.Button8.TabIndex = 34;
			this.Button8.Text = "Deletar Regedit";
			this.Button8.UseVisualStyleBackColor = false;
			this.Button9.BackColor = global::System.Drawing.Color.Transparent;
			this.Button9.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button9.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control button17 = this.Button9;
			location = new global::System.Drawing.Point(141, 168);
			button17.Location = location;
			this.Button9.Name = "Button9";
			global::System.Windows.Forms.Control button18 = this.Button9;
			size = new global::System.Drawing.Size(123, 26);
			button18.Size = size;
			this.Button9.TabIndex = 33;
			this.Button9.Text = "D. Mouse / Teclado";
			this.Button9.UseVisualStyleBackColor = false;
			this.Button10.BackColor = global::System.Drawing.Color.Transparent;
			this.Button10.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button10.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control button19 = this.Button10;
			location = new global::System.Drawing.Point(141, 136);
			button19.Location = location;
			this.Button10.Name = "Button10";
			global::System.Windows.Forms.Control button20 = this.Button10;
			size = new global::System.Drawing.Size(123, 26);
			button20.Size = size;
			this.Button10.TabIndex = 32;
			this.Button10.Text = "D. TaskManager";
			this.Button10.UseVisualStyleBackColor = false;
			this.Button11.BackColor = global::System.Drawing.Color.Transparent;
			this.Button11.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button11.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control button21 = this.Button11;
			location = new global::System.Drawing.Point(141, 105);
			button21.Location = location;
			this.Button11.Name = "Button11";
			global::System.Windows.Forms.Control button22 = this.Button11;
			size = new global::System.Drawing.Size(123, 25);
			button22.Size = size;
			this.Button11.TabIndex = 31;
			this.Button11.Text = "Drogar Mouse";
			this.Button11.UseVisualStyleBackColor = false;
			this.Button12.BackColor = global::System.Drawing.Color.Transparent;
			this.Button12.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button12.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control button23 = this.Button12;
			location = new global::System.Drawing.Point(141, 74);
			button23.Location = location;
			this.Button12.Name = "Button12";
			global::System.Windows.Forms.Control button24 = this.Button12;
			size = new global::System.Drawing.Size(123, 25);
			button24.Size = size;
			this.Button12.TabIndex = 30;
			this.Button12.Text = "Matar Explorer";
			this.Button12.UseVisualStyleBackColor = false;
			this.Button13.BackColor = global::System.Drawing.Color.Transparent;
			this.Button13.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button13.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control button25 = this.Button13;
			location = new global::System.Drawing.Point(141, 43);
			button25.Location = location;
			this.Button13.Name = "Button13";
			global::System.Windows.Forms.Control button26 = this.Button13;
			size = new global::System.Drawing.Size(123, 25);
			button26.Size = size;
			this.Button13.TabIndex = 29;
			this.Button13.Text = "Travar Todo PC";
			this.Button13.UseVisualStyleBackColor = false;
			this.Button14.BackColor = global::System.Drawing.Color.Transparent;
			this.Button14.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button14.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control button27 = this.Button14;
			location = new global::System.Drawing.Point(141, 12);
			button27.Location = location;
			this.Button14.Name = "Button14";
			global::System.Windows.Forms.Control button28 = this.Button14;
			size = new global::System.Drawing.Size(123, 25);
			button28.Size = size;
			this.Button14.TabIndex = 28;
			this.Button14.Text = "Criar 30k de Pastas";
			this.Button14.UseVisualStyleBackColor = false;
			this.Button7.BackColor = global::System.Drawing.Color.Transparent;
			this.Button7.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button7.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control button29 = this.Button7;
			location = new global::System.Drawing.Point(12, 200);
			button29.Location = location;
			this.Button7.Name = "Button7";
			global::System.Windows.Forms.Control button30 = this.Button7;
			size = new global::System.Drawing.Size(123, 26);
			button30.Size = size;
			this.Button7.TabIndex = 27;
			this.Button7.Text = "Deletar Win Defender";
			this.Button7.UseVisualStyleBackColor = false;
			this.Button6.BackColor = global::System.Drawing.Color.Transparent;
			this.Button6.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button6.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control button31 = this.Button6;
			location = new global::System.Drawing.Point(12, 168);
			button31.Location = location;
			this.Button6.Name = "Button6";
			global::System.Windows.Forms.Control button32 = this.Button6;
			size = new global::System.Drawing.Size(123, 26);
			button32.Size = size;
			this.Button6.TabIndex = 26;
			this.Button6.Text = "Deletar Cmd";
			this.Button6.UseVisualStyleBackColor = false;
			this.Button5.BackColor = global::System.Drawing.Color.Transparent;
			this.Button5.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button5.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control button33 = this.Button5;
			location = new global::System.Drawing.Point(12, 136);
			button33.Location = location;
			this.Button5.Name = "Button5";
			global::System.Windows.Forms.Control button34 = this.Button5;
			size = new global::System.Drawing.Size(123, 26);
			button34.Size = size;
			this.Button5.TabIndex = 25;
			this.Button5.Text = "Deletar Notepad";
			this.Button5.UseVisualStyleBackColor = false;
			this.Button4.BackColor = global::System.Drawing.Color.Transparent;
			this.Button4.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button4.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control button35 = this.Button4;
			location = new global::System.Drawing.Point(12, 105);
			button35.Location = location;
			this.Button4.Name = "Button4";
			global::System.Windows.Forms.Control button36 = this.Button4;
			size = new global::System.Drawing.Size(123, 25);
			button36.Size = size;
			this.Button4.TabIndex = 24;
			this.Button4.Text = "Deletar Windows";
			this.Button4.UseVisualStyleBackColor = false;
			this.Button3.BackColor = global::System.Drawing.Color.Transparent;
			this.Button3.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button3.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control button37 = this.Button3;
			location = new global::System.Drawing.Point(12, 74);
			button37.Location = location;
			this.Button3.Name = "Button3";
			global::System.Windows.Forms.Control button38 = this.Button3;
			size = new global::System.Drawing.Size(123, 25);
			button38.Size = size;
			this.Button3.TabIndex = 23;
			this.Button3.Text = "Fazer Logoff";
			this.Button3.UseVisualStyleBackColor = false;
			this.Button2.BackColor = global::System.Drawing.Color.Transparent;
			this.Button2.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button2.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control button39 = this.Button2;
			location = new global::System.Drawing.Point(12, 43);
			button39.Location = location;
			this.Button2.Name = "Button2";
			global::System.Windows.Forms.Control button40 = this.Button2;
			size = new global::System.Drawing.Size(123, 25);
			button40.Size = size;
			this.Button2.TabIndex = 22;
			this.Button2.Text = "Desligar PC";
			this.Button2.UseVisualStyleBackColor = false;
			this.Button1.BackColor = global::System.Drawing.Color.Transparent;
			this.Button1.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button1.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control button41 = this.Button1;
			location = new global::System.Drawing.Point(12, 12);
			button41.Location = location;
			this.Button1.Name = "Button1";
			global::System.Windows.Forms.Control button42 = this.Button1;
			size = new global::System.Drawing.Size(123, 25);
			button42.Size = size;
			this.Button1.TabIndex = 21;
			this.Button1.Text = "Reiniciar PC";
			this.Button1.UseVisualStyleBackColor = false;
			global::System.Windows.Forms.Control textBox = this.TextBox1;
			location = new global::System.Drawing.Point(12, 273);
			textBox.Location = location;
			this.TextBox1.Multiline = true;
			this.TextBox1.Name = "TextBox1";
			global::System.Windows.Forms.Control textBox2 = this.TextBox1;
			size = new global::System.Drawing.Size(381, 144);
			textBox2.Size = size;
			this.TextBox1.TabIndex = 42;
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = global::System.Drawing.SystemColors.ActiveCaptionText;
			size = new global::System.Drawing.Size(407, 243);
			this.ClientSize = size;
			this.Controls.Add(this.TextBox1);
			this.Controls.Add(this.Button15);
			this.Controls.Add(this.Button16);
			this.Controls.Add(this.Button17);
			this.Controls.Add(this.Button18);
			this.Controls.Add(this.Button19);
			this.Controls.Add(this.Button20);
			this.Controls.Add(this.Button21);
			this.Controls.Add(this.Button8);
			this.Controls.Add(this.Button9);
			this.Controls.Add(this.Button10);
			this.Controls.Add(this.Button11);
			this.Controls.Add(this.Button12);
			this.Controls.Add(this.Button13);
			this.Controls.Add(this.Button14);
			this.Controls.Add(this.Button7);
			this.Controls.Add(this.Button6);
			this.Controls.Add(this.Button5);
			this.Controls.Add(this.Button4);
			this.Controls.Add(this.Button3);
			this.Controls.Add(this.Button2);
			this.Controls.Add(this.Button1);
			this.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.Fixed3D;
			this.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "script";
			this.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "Sacanear";
			this.ResumeLayout(false);
			this.PerformLayout();
		}

		// Token: 0x040001A3 RID: 419
		private global::System.ComponentModel.IContainer components;
	}
}
